import type { MCPServer, User } from '@/types'

export const mockServers: MCPServer[] = [
  {
    id: '1',
    name: 'Kakao Map MCP',
    icon: '🗺️',
    publisher: 'Kakao Corporation',
    description:
      '카카오맵 API를 활용하여 장소 검색, 길찾기, 주변 정보를 제공하는 MCP 서버',
    toolsCount: 8,
    category: 'Maps & Location',
    status: 'online',
    verified: true,
    rating: 4.8,
    downloads: 12450,
    securityGrade: 'A',
    license: 'MIT',
    lastUpdated: '2일 전',
    authMethod: 'oauth',
    tools: [
      {
        id: 't1',
        name: 'searchPlace',
        description: '장소 검색',
        parameters: { query: 'string', x: 'number', y: 'number' },
      },
      {
        id: 't2',
        name: 'getDirections',
        description: '길찾기',
        parameters: { origin: 'string', destination: 'string' },
      },
      {
        id: 't3',
        name: 'getNearby',
        description: '주변 검색',
        parameters: { x: 'number', y: 'number', radius: 'number' },
      },
    ],
  },
  {
    id: '2',
    name: 'Weather Data Hub',
    icon: '🌤️',
    publisher: 'OpenWeather Team',
    description:
      '실시간 날씨 정보, 예보, 기상 데이터를 제공하는 글로벌 날씨 MCP 서버',
    toolsCount: 12,
    category: 'Weather & Environment',
    status: 'online',
    verified: true,
    rating: 4.6,
    downloads: 8920,
    securityGrade: 'A',
    license: 'Apache 2.0',
    lastUpdated: '1주 전',
    authMethod: 'apikey',
    tools: [
      {
        id: 't4',
        name: 'getCurrentWeather',
        description: '현재 날씨',
        parameters: { location: 'string' },
      },
      {
        id: 't5',
        name: 'getForecast',
        description: '일기예보',
        parameters: { location: 'string', days: 'number' },
      },
    ],
  },
  {
    id: '3',
    name: 'GitHub Integration MCP',
    icon: '🐙',
    publisher: 'GitHub Inc.',
    description:
      'GitHub 저장소 관리, 이슈 추적, PR 생성 및 코드 검색 기능을 제공하는 공식 MCP 서버',
    toolsCount: 15,
    category: 'Developer Tools',
    status: 'online',
    verified: true,
    rating: 4.9,
    downloads: 23100,
    securityGrade: 'A',
    license: 'MIT',
    lastUpdated: '3일 전',
    authMethod: 'oauth',
    tools: [
      {
        id: 't6',
        name: 'searchRepos',
        description: '저장소 검색',
        parameters: { query: 'string' },
      },
      {
        id: 't7',
        name: 'createIssue',
        description: '이슈 생성',
        parameters: { repo: 'string', title: 'string', body: 'string' },
      },
    ],
  },
  {
    id: '4',
    name: 'News Aggregator Pro',
    icon: '📰',
    publisher: 'NewsAPI',
    description:
      '전 세계 주요 언론사의 최신 뉴스를 수집하고 검색할 수 있는 뉴스 집계 서버',
    toolsCount: 6,
    category: 'News & Media',
    status: 'online',
    verified: false,
    rating: 4.3,
    downloads: 5670,
    securityGrade: 'B',
    license: 'Proprietary',
    lastUpdated: '5일 전',
    authMethod: 'apikey',
    tools: [
      {
        id: 't8',
        name: 'getTopHeadlines',
        description: '헤드라인 뉴스',
        parameters: { country: 'string', category: 'string' },
      },
    ],
  },
  {
    id: '5',
    name: 'Notion Workspace MCP',
    icon: '📝',
    publisher: 'Notion Labs',
    description:
      'Notion 데이터베이스와 페이지를 관리하고 검색할 수 있는 워크스페이스 통합 서버',
    toolsCount: 10,
    category: 'Productivity',
    status: 'online',
    verified: true,
    rating: 4.7,
    downloads: 15800,
    securityGrade: 'A',
    license: 'MIT',
    lastUpdated: '1일 전',
    authMethod: 'oauth',
    tools: [
      {
        id: 't9',
        name: 'searchPages',
        description: '페이지 검색',
        parameters: { query: 'string' },
      },
      {
        id: 't10',
        name: 'createPage',
        description: '페이지 생성',
        parameters: { parent: 'string', title: 'string' },
      },
    ],
  },
  {
    id: '6',
    name: 'Slack Connect',
    icon: '💬',
    publisher: 'Slack Technologies',
    description:
      'Slack 채널 관리, 메시지 전송, 사용자 정보 조회를 지원하는 팀 커뮤니케이션 서버',
    toolsCount: 14,
    category: 'Communication',
    status: 'degraded',
    verified: true,
    rating: 4.5,
    downloads: 9200,
    securityGrade: 'A',
    license: 'MIT',
    lastUpdated: '2주 전',
    authMethod: 'oauth',
    tools: [
      {
        id: 't11',
        name: 'sendMessage',
        description: '메시지 전송',
        parameters: { channel: 'string', text: 'string' },
      },
    ],
  },
  {
    id: '7',
    name: 'Database Query MCP',
    icon: '🗄️',
    publisher: 'DataTools Inc.',
    description:
      'PostgreSQL, MySQL, MongoDB 등 다양한 데이터베이스를 쿼리할 수 있는 범용 DB 서버',
    toolsCount: 20,
    category: 'Database',
    status: 'online',
    verified: false,
    rating: 4.2,
    downloads: 3400,
    securityGrade: 'B',
    license: 'Apache 2.0',
    lastUpdated: '1주 전',
    authMethod: 'apikey',
    tools: [
      {
        id: 't12',
        name: 'executeQuery',
        description: 'SQL 쿼리 실행',
        parameters: { query: 'string', database: 'string' },
      },
    ],
  },
  {
    id: '8',
    name: 'E-Commerce Analytics',
    icon: '📊',
    publisher: 'ShopMetrics',
    description:
      '쇼핑몰 판매 데이터, 고객 분석, 재고 관리를 위한 이커머스 분석 도구',
    toolsCount: 18,
    category: 'E-Commerce',
    status: 'online',
    verified: true,
    rating: 4.4,
    downloads: 6700,
    securityGrade: 'A',
    license: 'MIT',
    lastUpdated: '4일 전',
    authMethod: 'oauth',
    tools: [
      {
        id: 't13',
        name: 'getSalesData',
        description: '판매 데이터',
        parameters: { startDate: 'string', endDate: 'string' },
      },
    ],
  },
  {
    id: '9',
    name: 'AI Image Generator',
    icon: '🎨',
    publisher: 'CreativeAI',
    description:
      'DALL-E 및 Stable Diffusion을 활용한 AI 이미지 생성 및 편집 서버',
    toolsCount: 7,
    category: 'AI & ML',
    status: 'online',
    verified: false,
    rating: 4.6,
    downloads: 11200,
    securityGrade: 'C',
    license: 'Proprietary',
    lastUpdated: '6일 전',
    authMethod: 'apikey',
    tools: [
      {
        id: 't14',
        name: 'generateImage',
        description: '이미지 생성',
        parameters: { prompt: 'string', size: 'string' },
      },
    ],
  },
  {
    id: '10',
    name: 'Translation Hub',
    icon: '🌐',
    publisher: 'LangTech',
    description: '100개 이상의 언어를 지원하는 실시간 번역 및 언어 감지 서버',
    toolsCount: 5,
    category: 'Language & Translation',
    status: 'online',
    verified: true,
    rating: 4.8,
    downloads: 14500,
    securityGrade: 'A',
    license: 'MIT',
    lastUpdated: '3일 전',
    authMethod: 'apikey',
    tools: [
      {
        id: 't15',
        name: 'translate',
        description: '텍스트 번역',
        parameters: { text: 'string', from: 'string', to: 'string' },
      },
    ],
  },
  {
    id: '11',
    name: 'Finance Data API',
    icon: '💰',
    publisher: 'FinanceHub',
    description: '주식, 암호화폐, 환율 등 실시간 금융 데이터를 제공하는 서버',
    toolsCount: 16,
    category: 'Finance',
    status: 'online',
    verified: true,
    rating: 4.7,
    downloads: 8900,
    securityGrade: 'A',
    license: 'Apache 2.0',
    lastUpdated: '1일 전',
    authMethod: 'apikey',
    tools: [
      {
        id: 't16',
        name: 'getStockPrice',
        description: '주식 가격',
        parameters: { symbol: 'string' },
      },
    ],
  },
  {
    id: '12',
    name: 'Social Media Manager',
    icon: '📱',
    publisher: 'SocialTech',
    description:
      '트위터, 인스타그램, 페이스북 등 소셜 미디어 계정을 관리하는 통합 서버',
    toolsCount: 22,
    category: 'Social Media',
    status: 'online',
    verified: false,
    rating: 4.1,
    downloads: 4200,
    securityGrade: 'B',
    license: 'MIT',
    lastUpdated: '1주 전',
    authMethod: 'oauth',
    tools: [
      {
        id: 't17',
        name: 'postTweet',
        description: '트윗 게시',
        parameters: { text: 'string' },
      },
    ],
  },
]

export const mockStats = {
  totalServers: 1248,
  totalUsers: 45620,
  apiCalls: 8920450,
  activeToday: 12450,
  pendingApprovals: 23,
  healthyServers: 1180,
  degradedServers: 45,
  offlineServers: 23,
}

export const mockUsers: User[] = [
  {
    id: '1',
    username: 'developer1',
    email: 'dev1@example.com',
    role: 'Developer',
    serversCount: 3,
    lastActive: '2시간 전',
    status: 'Active',
  },
  {
    id: '2',
    username: 'admin_user',
    email: 'admin@example.com',
    role: 'Admin',
    serversCount: 0,
    lastActive: '5분 전',
    status: 'Active',
  },
  {
    id: '3',
    username: 'kakao_dev',
    email: 'kakao@example.com',
    role: 'Developer',
    serversCount: 1,
    lastActive: '1일 전',
    status: 'Active',
  },
  {
    id: '4',
    username: 'suspended_user',
    email: 'suspended@example.com',
    role: 'User',
    serversCount: 0,
    lastActive: '1주 전',
    status: 'Suspended',
  },
  {
    id: '5',
    username: 'pending_user',
    email: 'pending@example.com',
    role: 'Developer',
    serversCount: 0,
    lastActive: '방금',
    status: 'Pending',
  },
]
